name: algoquest
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
    sdk: ^3.9.2

dependencies:
    flutter:
        sdk: flutter
    flame: ^1.34.0
    flutter_riverpod: ^3.2.0
    go_router: ^17.0.1
    freezed: ^3.2.3
    freezed_annotation: ^3.1.0
    json_annotation: ^4.9.0
    drift: ^2.32.1
    path_provider: ^2.1.5
    path: ^1.9.1
    window_manager: ^0.5.1
    flutter_launcher_icons: ^0.14.4
    confetti: ^0.8.0

dev_dependencies:
    flutter_test:
        sdk: flutter
    integration_test:
        sdk: flutter
    flutter_lints: ^5.0.0
    json_serializable: ^6.11.2
    build_runner: ^2.7.1
    drift_dev: ^2.32.1

flutter:
    uses-material-design: true
    assets:
        - assets/data/
        - assets/data/levels/
        - assets/data/challenges/
        - assets/images/

flutter_launcher_icons:
    android: "launcher_icon"
    ios: true
    image_path: "./assets/images/icon.png"
    min_sdk_android: 21 # android min sdk min:16, default 21
    web:
        generate: true
        image_path: "./assets/images/icon.png"
    windows:
        generate: true
        image_path: "./assets/images/icon.png"
        icon_size: 256 # min:48, max:256, default: 48
    macos:
        generate: true
        image_path: "./assets/images/icon.png"
